
services:
    apache-service:
        image: httpd:2.4-alpine
        container_name: steakhouse
        restart: always
        ports:
            - 81:80
        volumes:
            - ./website:/usr/local/apache2/htdocs